### ISSUE TITLE
apiのバリデーション

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#13]
無くてもしばらくは困らないので出来るときにでも。
今思いつくのは以下

登録api
- 座標の項目必須
- 座標が有効か

バリデーションじゃないけど、パスコード生成はユニークにさせるように

取得api
- パスコードの項目必須
- パスコードの形式

なければ404でも。

**Comment by h-haraguchi** [comment]
今月内にはできそうなのでマイルストーンに入れときます。

**Comment by h-haraguchi** [comment]
https://www.npmjs.com/package/express-validation

こいつ使えそう

**Comment by h-haraguchi** [comment]
https://github.com/express-validator/express-validator

こっちの方がstar多いな。どっちがいいだろう。

**Comment by h-haraguchi** [comment]
間違えて #9 位置情報APIのリクエスト のブランチにcommitを入れてしまった。
#9 でレビューオナシャス

**Comment by h-haraguchi** [comment]
こちらもまーじされたので完了！
