### ISSUE TITLE
APIの環境切替を可能にする

### ISSUE THREAD

**Issue by h-haraguchi** [tamakon/imakoko#14]
APIで使用するfirebaseのプロジェクトを開発環境と本番環境で分けたい。
この対応はそこまで重要ではない。

**Comment by h-haraguchi** [comment]
https://firebase.google.com/docs/configure/
開発環境と本番環境の切り替えはinitializeAppのconfigの切り分けでやるしか無いらしいな。
https://firebase.google.com/docs/functions/config-env
こいつを使うのだろうか。
https://firebase.google.com/docs/reference/admin/node/admin#.initializeApp
ここに書いてあるFIREBASE_CONFIGって環境変数のことか。理解した。
https://stackoverflow.com/questions/49697517/firebase-cloud-function-process-env-firebase-config-not-working-after-1-0-0-with

**Comment by h-haraguchi** [comment]
最強の解決案を発見。
https://firebase.googleblog.com/2016/07/deploy-to-multiple-environments-with.html?m=1

**Comment by tronperidot** [comment]
それはデプロイ先の切り替えが出来るって話で、コンフィグファイルを用意しなくていい理由にはならないと思うけど？

**Comment by h-haraguchi** [comment]
デプロイ先のプロジェクトが切り替わると、cloud function のinitializeAppのデフォルトのconfigもそのプロジェクトのconfigを見に行くようになるから問題なくなるってこと。
ただ、initializeApp になんのパラメータも入れないって言う前提にはなる。
また、それが果たして可能なのかって話にもなる。あんまり最強じゃなかったな。

**Comment by tronperidot** [comment]
ごめん、configは必ず作る想定で進めているのかと思った。

**Comment by h-haraguchi** [comment]
クライアントアプリ側のinitializeAppはoptions必須だから、デフォルトconfigでプロジェクト分岐はやっぱりあんまり現実的じゃないかもなー
https://firebase.google.com/docs/reference/node/firebase?hl=ja#.initializeApp

**Comment by h-haraguchi** [comment]
とりあえずいろいろ調べて環境変数`FIREBASE_CONFIG`は俺たちがいじれる設定ではないことがわかった。
たどり着いた結論は`.runtimeconfig.json`を動的に作ってどうにかするという対処法。
`function:config:set` とかは使い勝手が悪すぎるので使いたくない。

今は`production.json`と`development.json`を直下においておき、どちらかを`.runtimeconfig.json`に`cp`して使う形になってるけど、ここはどうするか検討中。
@tronperidot  Google Drive に置くとしたらダウンロードするときに認証とか必要になるかな？

**Comment by tronperidot** [comment]
自動で出来るならそれが一番だけど、Google Driveファイル置いて認証するために認証やるとなると本末転倒な気がするしGoogle Driveに置くのは俺らのためのバックアップファイル置くだけで、デプロイ時は手動で上げるのは仕方ないような気がしてきた。

firebase cpコマンドみたいなのがあるかなと思ったけど、見当たらなかったので、firebase deployする直前にローカルでconfigファイル差し替える原始的なやり方になってしまうんじゃないかな。

**Comment by tronperidot** [comment]
firebaseのプロジェクト自信にGoogle Driveの認証を付与できるなら、deploy時にpre,postスクリプトをhookとして作成できるみたいだから、そこにconfigのダウンロードスクリプトを織り交ぜるとか？
まあ、このhookスクリプトにしてもio使えるのかとかルートディレクトリ認識しているのかとか色々課題はあるのは間違いなさそう。 

ここまで来たらプライベートにJenkinsサーバ構築しようぜとかそういう話になりそう（笑）

**Comment by h-haraguchi** [comment]
とりあえず、環境設定ファイルはgithubに直置きすることにしますw

**Comment by h-haraguchi** [comment]
マージされたのでクローズ！
