### ISSUE TITLE
dotenvの追加

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#17]
少なくともgoogle mapsのapiキーを格納したい

**Comment by h-haraguchi** [comment]
API側もdotenvに対応しましたー。https://github.com/tamakon/imakoko/commit/a39e97b1e02b2d92d58881ed31f4493d2c0d9421
`feature/add-google-map` の実装(作成された.env.sampleファイル)に依存してるから、`feature/add-google-map`がマージされたあとにプルリクとかは出します。

**Comment by tronperidot** [comment]
マージしたので閉じます
