### ISSUE TITLE
動的に生成されたパスをリロードするとエラーページが表示される

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#22]
/find/_id/map
のページをリロードすると発生した。

エラーページを表示させないように修正するとして、現在はfirebaseのエラーページが直で表示されてしまうので、エラーページも別途用意したほうが良さそう。

**Comment by tronperidot** [comment]
mnrだとエラーにならない。
/findとかは問題ない。
/find/_idのページを作成していないのが原因か？
直リンしても一階層順番に解決していってるのかな？

**Comment by h-haraguchi** [comment]
`nuxt --spa`で起動した場合は起こらなかった。
`nuxt generate; firebase serve`で起動した場合は起こった。
https://ja.nuxtjs.org/guide/routing/

> 警告: generate コマンドでは 動的なルーティング は無視されます。 : generate 設定 API

こいつが限りなく怪しい。

**Comment by h-haraguchi** [comment]
https://nuxtjs.org/api/configuration-generate#routes
設定ファイルでPromissやるかFirebaseやめるかw

**Comment by tronperidot** [comment]
やりたいこと変わらんし一旦、promise実装する方針で進まます！

**Comment by tronperidot** [comment]
あと、エラーページはアプリケーションが食えばいいかなって考えています。
なのでnuxt側でページ作るよ

**Comment by tronperidot** [comment]
Promiseダメそうだわ。
これ結局動的な数だけ静的なページを作るって話っぽい。
なので1万通りあったら1万ページ作りそうw

**Comment by h-haraguchi** [comment]
まじかｗｗ
たしかにgenerateってそういうことだもんな。

**Comment by h-haraguchi** [comment]
これが取りうる手段かな。

- `generate`やめる。(`firebase function`でssr)
- 動的パスをやめる(パラメータでどうにかする)
- firebaseやめる(Herokuにする)

やっぱ一番いいのはssrかな。本来的だし。
明日(いや今日か)、ちょっとssrで`firebase function`頑張ってみるわ。

**Comment by tronperidot** [comment]
実はクライアント側も利用しているGoogleMapのライブラリはssr非対応で対策が必要だったりする

**Comment by h-haraguchi** [comment]
現在色々頑張っていてssrで表示できるようにはなったが、element-uiのタグが変換されない。
しかも、npm run devの方はリロードを繰り返すような変な挙動をしているｗ

**Comment by h-haraguchi** [comment]
`buildDir`を指定すると`element-ui`が機能しなくなることがわかった。

**Comment by h-haraguchi** [comment]
間違えてcloseしちゃったｗ

**Comment by h-haraguchi** [comment]
きたわ。

**Comment by h-haraguchi** [comment]
nodejsが6までしか対応できてなくてnodejs8以上が前提のnuxtがデプロイできないｗｗｗ

**Comment by tronperidot** [comment]
ダメだこりゃw
むしろnuxt側の方を違う言語に変える？w

**Comment by h-haraguchi** [comment]
一応デプロイまでこぎつけたのに、アウトバウンドネットワーキングがsparkプランだとだめとのことでできない。。。
なんだ、Google以外の外部のAPIなんて使っとらんぞ。

**Comment by tronperidot** [comment]
google maps apiはfirebaseからみて同じになっていないとか？

**Comment by h-haraguchi** [comment]
https://github.com/tamakon/imakoko/tree/ssr-firebase
一応、`firebase-serve`まではできる。問題はデプロイｗ
https://imakoko-dev.firebaseapp.com/api/locations/?passcode=4283
APIの方は実行できるから画面の方でなんか外部APIを使ってるのかな。

**Comment by h-haraguchi** [comment]
> google maps apiはfirebaseからみて同じになっていないとか？

そうっぽいですｗ くそぅ！
https://stackoverflow.com/questions/48168873/firebase-functions-external-network-is-not-accessible-and-quotas-are-severely-l?rq=1

**Comment by h-haraguchi** [comment]
一応共有しておくと、firebaseがnodejsV6までしか対応してなくてV8からサポートのnuxtが動かない問題はnuxtのバージョンを下げて解決(1.0.0-rc11)
`buildDir`を指定すると`element-ui`が機能しなくなる問題は、デフォルトの設定(`.nuxt`)でビルドしたあと、`cp`コマンドで移動して解決ｗ
あと、原因不明だけど、firebase側でのnuxtの設定は`dev: false`にしないと起動後に止まるｗ

**Comment by tronperidot** [comment]
話し戻してssrだとかなり手間そうだし、nuxt側が動的パスを消してquery paramsでどうにかする方針に変更してやってみようかと思う。

**Comment by tronperidot** [comment]
query paramsは取り消して、アプリをhashモードにして起動するように修正した。

**Comment by tronperidot** [comment]
vue-routerの `mode: hash` で解決した
