### ISSUE TITLE
firebaseの利用状況をslackとかで知りたい

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#31]
ほとんど無いと思うけど万が一無料リクエストを越えるようなことはあまりしたくないので、
firebaseのCloudFunctionとかのリクエストで一定のリクエスト超えたらアラートとかデイリーなのかとかで、slack等に通知できると嬉しい。

**Comment by h-haraguchi** [comment]
請求先アカウントがないとできないくさい？
https://cloud.google.com/billing/docs/how-to/budgets?hl=ja

**Comment by tronperidot** [comment]
アラート機能でできるかと思ってたらそれ請求プラン以上なのかな。
だとしたらfirebase-toolsのcliで確認できなければ諦める方針かな～

**Comment by tronperidot** [comment]
取得できなさそうなので諦めた。
