### ISSUE TITLE
firebaseにデプロイ完了したらslackへ通知

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#32]
firebaseにhook機能が設けられているのか？
なければnpm scriptsに追加でpost scriptを書く感じかな

**Comment by h-haraguchi** [comment]
firebase.json の `postdeploy` でできるんだが、SlackのwebhookのURLがソースコード内に入ることになってしまうなぁ。

**Comment by tronperidot** [comment]
これにもenvいけたりしないんかな？

**Comment by h-haraguchi** [comment]
.envでもいけるで。ただ、.envにするにしても、.env.sampleにはURLいれんといかんねぇ。
GOOGLE_MAPS_APIの値みたいにしとけばいいかな？
とりあえず.envで作ってみるか。

**Comment by tronperidot** [comment]
そうだね、サンプルなんだからそれがなにか分かるだけでいいんだよ。
それを使える必要はない

**Comment by h-haraguchi** [comment]
マージされたのでくろーず。
