### ISSUE TITLE
GPSの位置情報取得

### ISSUE THREAD

**Issue by tronperidot** [tamakon/imakoko#7]
firebaseに位置情報を送るためにローカルデバイスから位置情報を取得する必要がある。

**Comment by tronperidot** [comment]
html5 ではnavigatorオブジェクトの中に位置情報取得のイベントを提供してくれている
https://developer.mozilla.org/ja/docs/Web/API/Geolocation/Using_geolocation

**Comment by tronperidot** [comment]
うーん、前やった時は問題なく普通に取れていたんだけど、実機のandroid8.0で今試したらうまくいかない。
ダメかもわからんね。

**Comment by tronperidot** [comment]
もしかしてと思って調べたら、やっぱり。
https://developers.google.com/web/fundamentals/native-hardware/user-location/?hl=ja
ローカルサーバが今はhttpだからダメなのか？
確認するためにローカルでhttpsの起動を行う方法を調べないと

**Comment by h-haraguchi** [comment]
自己証明書が必要になりそうな案件ですな

**Comment by h-haraguchi** [comment]
位置情報としては、多分このオブジェクト使うと思うけど、どのプロパティ使う？
https://developer.mozilla.org/en-US/docs/Web/API/Coordinates

longtudeとlatitudeぐらい？

**Comment by tronperidot** [comment]
> longtudeとlatitudeぐらい？

現状考えてるのはそれだけです！

**Comment by tronperidot** [comment]
localではhttpで立ち上げてるので、androidだとうまく確認できない。
ただし、httpsのサーバで確認したら正常に確認できた。
なので、導入自体は正しく出来てるのでクローズします
